version = 0.1

[default.deploy.parameters]
stack_name = "page"
resolve_s3 = true
s3_prefix = "page"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ResendApiKey=\"__SET_ME__\" ContactToEmail=\"marwan.gendy@gmail.com\" ContactFromEmail=\"Recruit <recruit@marwanelgendy.link>\" ContactReportEmail=\"marwan.gendy@gmail.com\" AlarmEmail=\"marwan.gendy@gmail.com\" AdminApiKey=\"__SET_ME__\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
