#!/usr/bin/env python3
"""
Generate .secrets/config.generated.env from .secrets/config.manifest.json.

This mirrors the secrets flow:
- secrets manifest -> deploy.generated.env (from Secrets Manager ARNs)
- config manifest  -> config.generated.env (from local config values)
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def sh_single_quote(value: str) -> str:
    return str(value).replace("'", "'\\''")


def main() -> None:
    ap = argparse.ArgumentParser(description="Seed config env exports from config manifest")
    ap.add_argument(
      "--secrets-dir",
      type=Path,
      default=Path(".secrets"),
      help="Directory containing config.manifest.json (default: .secrets)",
    )
    args = ap.parse_args()

    base = args.secrets_dir.expanduser().resolve()
    manifest_path = base / "config.manifest.json"
    if not manifest_path.is_file():
        print(f"error: missing {manifest_path}", file=sys.stderr)
        raise SystemExit(2)

    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    if int(data.get("version", 1)) != 1:
        print("error: unsupported config manifest version", file=sys.stderr)
        raise SystemExit(2)

    exports: list[tuple[str, str]] = []
    for entry in data.get("configs", []):
        name = entry.get("name")
        value = entry.get("value")
        required = bool(entry.get("required", False))
        if not name:
            print("error: each config entry requires 'name'", file=sys.stderr)
            raise SystemExit(2)
        if value is None:
            if required:
                print(f"error: config '{name}' is required but missing value", file=sys.stderr)
                raise SystemExit(2)
            continue
        exports.append((name, str(value)))

    out = base / "config.generated.env"
    lines = ["# Generated by scripts/seed_local_configs.py — do not commit"]
    if exports:
        for name, value in exports:
            lines.append(f"export {name}='{sh_single_quote(value)}'")
    else:
        lines.append("# (no config entries)")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
